# version.patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  namespace: tpisula
spec:
  template:
    spec:
      containers:
        - name: resume
          image: ghcr.io/tomp736/resume/resume:main
          imagePullPolicy: Always